umrover/mrover-workspace

- onboard_teleop/src/__main__.py
- rover_msgs/Joystick.lcm
- rover_msgs/Motors.lcm
> [lcm] added joystick and motor lcm. Added subscription for joystick

- onboard/hwi/src/__main__.py
- onboard/talon/src/__main__.py
- onboard/teleop/src/__main__.py
- rover_common/src/talon_srx.py
- rover_msgs/DriveMotors.lcm
Also, renames Motors to DriveMotors.
> [HWI] High level API for driving with talons. 

- onboard/talon/project.ini
- onboard/talon/src/__main__.py
- onboard/talon/src/lowlevel.py
- rover_common/src/talon_srx.py
- rover_msgs/Encoder.lcm
- rover_msgs/SetParam.lcm
for encoder and set and param.
> [HWI] Add lcm and high level talon srx integration

- ansible/onboard.yml
- ansible/roles/onboard_services/files/rover-hwi.service
- ansible/roles/onboard_services/files/rover-onboard-teleop.service
- onboard/talon/src/lowlevel.py
- onboard/teleop/src/__main__.py
User of onboard is nvidia
[hwi] Fix making param an int.
> [ansible] service files start on boot.

- base_station/gui/src/components/PidTune.html
- onboard/talon/src/__main__.py
- rover_msgs/Encoder.lcm
Change encoder values to be 32 bit.
> Make encoder values 32bit

- onboard/odometry/src/__main__.py
odometry message forwarding now uses aiocan.
> [hwi] Update odometry message forwarding

- base_station/gui_webpack/src/components/Cameras.vue
- base_station/gui_webpack/src/components/Dashboard.vue
- base_station/gui_webpack/src/components/RoverMap.vue
- base_station/gui_webpack/src/components/Sensors.vue
- base_station/gui_webpack/src/components/WaypointEditor.vue
- base_station/gui_webpack/src/store/modules/autonomy.js
- lcm_bridge/client/dist/bridge.js
[gui] Components can now register to channels with a callback
[gui] Rover map now shows waypoints not added to the route
[gui] Sensors has been refactored to use callbacks
[gui] Camera connection status properly works
[gui] driving connection light now properly works
> [gui] Updates to bridge, rover map, and sensors, and camera lights

- onboard/cv/main.cpp
- onboard/cv/obstacle_detector.cpp
- onboard/cv/perception.hpp
I'm really sorry there might be several merge conflicts, please let me know if there's an issue.
> [cv] added split window function

- jarvis_files/jarvis_cmd/src/jarvis/third_party.py
Check if rapidjson is already installed before installing.
> [jarvis] fix rapidjson check

- base_station/blender_router/project.ini
- base_station/blender_router/src/__main__.py
- base_station/gui_webpack/src/components/WaypointEditor.vue
- rover_msgs/SetParam.lcm
[gui] fixed indentation for SetParam.lcm
[gui] auton button now properly connects to other components
> [gui] added blender router program that routes blender socket messages to lcm

- base_station/gui_webpack/src/components/Cameras.vue
- onboard/ra/project.ini
- onboard/ra/src/__main__.py
Added joystick buttons to change camera and decoding for robotic arm
> Camera and Arm Work

- base_station/blender_router/src/__main__.py
- base_station/gui/src/components/Controls.vue
- base_station/gui/src/components/WaypointEditor.vue
Reverts umrover/mrover-workspace#104
> Revert "Added Xbox controls for Blender IK"

- simulators/nav/src/components/App.html
- simulators/nav/src/components/UploadTestButton.html
- simulators/nav/testing/test_dummy.json
This patch adds the ability to upload test cases on the nav simulator.
> [nav] Add test file uploading to simulator

- onboard/filter/src/__main__.py
- onboard/filter/src/rawmessages.py
- onboard/filter/unintegrated/rawmsgs.py
This change restructures the sensor fusion base code to allow for easier building of future sensor fusion. Additionally, the change fixes a bug in the calculating of bearing.
> [nav-filter] Restructure filter base

- base_station/blender_router/src/__main__.py
- base_station/gui/src/components/Controls.vue
- base_station/gui/src/components/PidChart.vue
- base_station/gui/src/components/PidTune.vue
- Blender model will correctly switch between FK and IK modes (Model should mirror arm in FK mode)
- Joint E moves faster in IK mode
- Random jumps in arm position are filtered out
> [teleop] IK Control improvements

- base_station/gui/src/components/Controls.vue
- base_station/gui/src/components/Dashboard.vue
- base_station/gui/src/components/SAControls.vue
- base_station/gui/src/components/SATask.vue
- base_station/gui/src/router/index.js
- onboard/teleop/src/__main__.py
- rover_msgs/SAMotors.lcm
- rover_msgs/TalonConfig.lcm
- rover_msgs/Xbox.lcm
removed extra comments
[teleop] several small changes
> [teleop] Soil Acquisition GUI page

- ansible/roles/base_station_services/files/rover-base_station_microscope.service
- ansible/roles/base_station_services/tasks/main.yml
- base_station/gui/src/components/Cameras.vue
- base_station/gui/src/components/LCMEcho.vue
- onboard/microscope/project.ini
- onboard/microscope/src/__main__.py
- rover_msgs/Microscope.lcm
[teleop] several more gstreamer midifications
[teleop] fixed microscope gst ip
[teleop] added microscope to echo page
[teleop] set gst state to PLAYING/PAUSED for microscope
> [teleop] microscope gstreamer code for jetson and base station

- config/nav/config.json
- onboard/nav/rover.cpp
- onboard/nav/stateMachine.cpp
This change also corrects a bug with the driving power
> Added dampen to config file and modified other config file features

- onboard/nav/stateMachine.cpp
- onboard/nav/stateMachine.hpp
- rover_msgs/ProximitySensors.lcm
This change adds the infrastructure needed for the proximity sensor LCMs and sets up Nav to accept the multiple obstacle messages.
> [nav] add proximity sensor LCM

- base_station/gui/src/components/WaypointEditor.vue
- onboard/nav/rover.cpp
- onboard/nav/rover.hpp
- onboard/nav/searcher.cpp
- onboard/nav/stateMachine.cpp
- onboard/nav/stateMachine.hpp
- onboard/talon/main.cpp
- rover_msgs/NavStatus.lcm
- rover_msgs/TalonConfig.lcm
- simulators/nav/src/components/App.html
Added ability for rover to track the amount of tennis balls found, simulator can receive and display this data. Counter also visible in base_station gui, receives tennis ball data from rover.
> [nav] added completed tennis balls counter to nav, simulator, base station gui

- onboard/filter/src/__main__.py
- onboard/filter/src/filterObjects.py
- onboard/filter/src/rawmessages.py
Caution: LocationFilter1 is still under construction
> [nav-filter] implement first version of sensor fusion algorithm

- jarvis_files/requirements.txt
Security issue in previous version.
> [jarvis] Upgrade Jinja to 2.10.1

- onboard/gps/src/__main__.py
Add checks for the direction of the gps when parsing.
> [Nav-Filter] Add checks for the direction of the gps when parsing.

- onboard/nav/searcher.cpp
- onboard/nav/stateMachine.cpp
Fixes bugs with rover not turning off and not pausing correctly
> Add stop commands to force rover to stop

- jarvis
Reverts umrover/mrover-workspace#187
> Revert "[Jarvis] Now replaces forward slashes with underscores to allow build…"

- onboard/science_controls/src/__main__.py
By request of Kitty and Rachel.
> [sa] Removed ammonia test automatic servo controls.

- base_station/gui/src/components/AutonJoystickReading.vue
- base_station/gui/src/components/AutonTask.vue
- base_station/gui/src/components/Menu.vue
- base_station/gui/src/components/RawSensorData.vue
- base_station/gui/src/components/RoverMapAuton.vue
- base_station/gui/src/components/SensorsAuton.vue
- base_station/gui/src/components/WaypointEditor_Auton.vue
- base_station/gui/src/components/WaypointItem_Auton.vue
- base_station/gui/src/router/index.js
- rover_msgs/Waypoint.lcm
Initial version of the Auton GUI page.
Note: there is a bug when dragging the map. This will be fixed in a future commit.
> [nav-sim] Create auton gui page

- simulators/nav/src/components/App.html
- simulators/nav/src/components/DrawModeSelector.html
- simulators/nav/src/components/SimulatedItemDisplay.html
- simulators/nav/src/components/SimulatorField.html
- simulators/nav/src/constants.js
Nav simulator should have the added ability to simulate gates.
> [Nav] Updated simulator to include gate functionality

- beaglebone/mosfets/src/__main__.py
- rover_msgs/Mosfet.lcm
- rover_msgs/MosfetCmd.lcm
@prabid Please note the new channel name and LCM struct used for mosfets for when you update the GUI controls for GPIO devices.
> [beaglebone] refactored mosfet program

- onboard/nav/gate_search/gateStateMachine.cpp
- onboard/nav/utilities.cpp
Always drive to the center point (point centered in front of gate) that is closer so we don't run over a gate post.
> [nav] Always drive to closest center point in gate search

- onboard/nav/stateMachine.cpp
- simulators/nav/src/.eslintrc.js
- simulators/nav/src/components/NavSimulator.vue
- simulators/nav/src/components/common/BinaryIndicator.vue
- simulators/nav/src/components/common/HeartbeatMonitor.vue
- simulators/nav/src/components/control_panel/DebugTools.vue
- simulators/nav/src/components/control_panel/DrawModule.vue
- simulators/nav/src/components/control_panel/SimSettings.vue
- simulators/nav/src/components/field/Field.vue
- simulators/nav/src/components/field/reference_points.ts
- simulators/nav/src/components/field/rover.ts
- simulators/nav/src/components/field_items/FieldItems.vue
- simulators/nav/src/components/field_items/ReferencePointItem.vue
- simulators/nav/src/components/header/Header.vue
- simulators/nav/src/components/perception/Perception.vue
- simulators/nav/src/store/modules/fieldState.ts
- simulators/nav/src/store/modules/simulatorState.ts
- simulators/nav/src/utils/types.ts
- simulators/nav/src/utils/utils.ts
* Enable indicator lights conveying connection to other services.
* Draw rover's path
* Add reference point draw mode
> Add simulator features.

- beaglebone/servo/src/__main__.py
servos 0 & 1 were switched in wiring the science box - updated the code to reflect that
> [esw] servo code update

- beaglebone/accelerometer/src/accel.py
- beaglebone/imu/src/imu.py
- beaglebone/imu/src/mux.py
this time actually added the files
> muxed IMU with git add

- ansible/roles/jetson_networks/files/rover.network
See this issue for more info: https://github.com/OE4T/meta-tegra/issues/146
> Fixed issue with LLDP packet sent from Ubiquiti Rockets hanging the Jetson

- jetson/nav/main.cpp
- jetson/nav/stateMachine.cpp
commented out incomplete/buggy radio repeater code which caused seg faults in testing with fake rover
clean up comments
> [nav] remove radio repeater code that causes seg faults in tests

- base_station/gui/src/components/AutonJoystickReading.vue
- base_station/gui/src/components/AutonTask.vue
- base_station/gui/src/components/Obstacle.vue
- base_station/gui/src/components/OdometryReading.vue
- base_station/gui/src/components/RadioSignalStrength copy.vue
- base_station/gui/src/components/RawSensorData.vue
- base_station/gui/src/components/TargetList.vue
- base_station/gui/src/components/WaypointEditor_Auton.vue
- base_station/gui/src/static/rover_msgs.json
Added raw data LCMs in the scrollable area under the camera box, fix a bug where adding too many waypoints to the waypoint editor would squish the boxes above it, moved top right odom reading to be inline with the other data in that area.
> [gui] Auton GUI Redesign, raw data, waypoint editor fixes etc.

- jetson/teleop/src/__main__.py
added teleop's file for stopping motors
> [teleop] turn off motors when nav is killed from command line

- simulators/nav/src/store/modules/fieldState.ts
resolve #613 
fix sim bug where test case json files weren't downloading
note that I am putting this in both main and auton_integration because I want the improved sim to be accessible
> fixed json file not downloading

- config/nav/config.json
- jetson/nav/gate_search/gateStateMachine.cpp
update far gate centerpoint destination to be further to allow rover to cross through fully
> [nav] update far gate centerpoint destination 

- jetson/science_bridge/README.md
- jetson/science_bridge/src/__main__.py
> science bridge code 

- jetson/percep_obs_detect/.gitignore
- jetson/percep_obs_detect/src/euclidean-cluster.cu
> Fixed voxelGrid checking neighbor bins

- jetson/percep_obs_detect/include/viewer.hpp
- jetson/percep_obs_detect/src/obs-detector.cu
- jetson/percep_obs_detect/src/viewer.cpp
> Added visualizer rotation around an arbitrary target

- jetson/filter/src/conversions.py
- jetson/filter/src/inputs.py
Uses the roll, pitch, yaw to remove gravity from the robot-frame acceleration
> Remove gravity from acceleration in LKF

- jetson/filter/src/__main__.py
- jetson/filter/src/conversions.py
- jetson/filter/src/inputs.py
The filter will no longer assume no movement when there are no received nav state lcms.
> Remove static assumption with no nav state

- jetson/percep_obs_detect/include/reader.h
- jetson/percep_obs_detect/include/writer.h
Class to write point cloud to filesystem from GPU
> Add PCDWriter

- jetson/teleop/src/__main__.py
Reopening again, hopefully with Travis fixed. Flips polarity of auton controls
> Auton reverse

- config/nav/config.json
- jetson/nav/gate_search/diamondGateSearch.cpp
- jetson/nav/gate_search/gateStateMachine.cpp
- jetson/nav/gate_search/gateStateMachine.hpp
- jetson/nav/obstacle_avoidance/obstacleAvoidanceStateMachine.cpp
- jetson/nav/rover.cpp
- jetson/nav/rover.hpp
- jetson/nav/search/searchStateMachine.cpp
- jetson/nav/stateMachine.cpp
- jetson/nav/stateMachine.hpp
- jetson/nav/utilities.cpp
From the previous `auton_integration` branch, should be updated with all the necessary main changes, let's try to get this merged in (already tested and was previously merged in the old branch)
> Gate Traversal PR Code

- jetson/percep_obs_detect/CMakeLists.txt
- jetson/percep_obs_detect/include/find-clear-path.hpp
- jetson/percep_obs_detect/include/obs-detector.h
- jetson/percep_obs_detect/src/find-clear-path.cu
- jetson/percep_obs_detect/src/obs-detector.cu
Added code to detect distance to nearest obstacle and populate LCM
> Nearest obs

- jetson/teleop/src/__main__.py
Change made due to gearboxes switching direction of travel.
resolves #856
> [teleop] Flip drive polarity

- jetson/nav/rover.cpp
Changes from 2/16 testing, made sure that driving forward is always full power and that the 25% reduction of power is removed.
> [nav] Changed driving power

- base_station/gui/src/components/StripTest.vue
Added button in strip test that current strip to start angle. Also added text box where a user can manually change the angle of the current strip.
> [teleop] Add start button

- base_station/gui/src/components/RawSensorData.vue
> [teleop] Add calibration data to auton GUI

- jetson/percep/artag_detector.cpp
- jetson/percep/camera.cpp
uses correct dictionary, removes corner refinement, removes brightness setting
> ar tag fixes

- base_station/gui/src/components/Amino.vue
- base_station/gui/src/components/Carousel.vue
- base_station/gui/src/components/Chlorophyll.vue
- base_station/gui/src/components/StripTest.vue
Updated the following files that used A/B/C with underlying 2/1/0 values to 0/1/2:
- StripTest.vue (Strip Test Controls)
- Amino.vue (Heater controls)
- Carousel.vue
- Chlorophyll.vue (Chlorophyll Spectral data table)
> [teleop] Changed Science GUI from A/B/C to displaying 0/1/2

- jetson/odrive_bridge/src/__main__.py
watchdog timer somehow got deleted in pervious merge
> [esw] Drive watchdog bug fix

- jetson/nav/search/spiralOutSearch.cpp
- jetson/nav/stateMachine.cpp
Removes the intermediate points from the search, function is still in there just in case. Also, checks if we are immediately at the first point
> [nav] Remove intermediate, include change for checking if immediately at point

- base_station/gui/src/components/Amino.vue
Since it was mentioned that heaters could not be turned off from the GUI, I've changed how the toggle buttons work. Before, if we did not have confirmation that ESW had turned a heater on, we could only send 'on' commands. Now, if we haven't received confirmation, the commands we send will alternate between on and off.
> [teleop GUI] Allow heaters to be turned off without being confirmed on

- base_station/gui/src/components/StripTest.vue
Added additional functionality to the striptest component
> Added striptest back to start and user input functionality

- base_station/gui/src/components/StripTest.vue
> [teleop GUI] Fix strip test custom controls

- base_station/gui/src/components/Carousel.vue
> [teleop] Changed carousel drop down to three buttons

- base_station/gui/src/components/RoverMap.vue
Includes background and centers on rover in first odometry reading
> [teleop] Update ERD map

- jarvis_files/jarvis_cmd/src/jarvis/__main__.py
- jarvis_files/jarvis_cmd/src/jarvis/launch.py
* Specify the -r flag to run only and not build
* Added the export LCM command, which will be executed anytime launch is called
* Added commands to localization launch
> Jarvis Launch Changes

- base_station/gui/src/components/SaveAutonData.vue
Previous PRs screwed each other up :/
I don't know for sure how long the logging can last
> [teleop] Log fix

- .gitignore
- base_station/download_map/project.ini
- base_station/download_map/src/__main__.py
- base_station/gui/src/components/ERDRoverMap.vue
- base_station/gui/src/components/RoverMapAuton.vue
- pip_deps/requirements.txt
The checkbox in the bottom left of the map will toggle whether the map uses the openstreetmap webapi or the static/map directory to use local tiles. 
Google doc explaining setup:
https://docs.google.com/document/d/1gc2yv4KhZgtrdS6AzUc37DAglwTzC9N3XXtQOB86pQw/edit
> [Auton-GUI] Added functionality for offline map viewing

- base_station/gui/src/components/ArmControls.vue
- base_station/gui/src/components/ERDTask.vue
- base_station/gui/src/components/ERDWaypointEditor.vue
- base_station/gui/src/components/ESTask.vue
- base_station/gui/src/components/EncoderCounts.vue
Made map a fixed height, set fixed height on waypoint list (but can still scroll)
> [teleop] Reformat ERD waypoint editor, map

- ansible/roles/science_services/files/rover-science-raman.service
not sure how this slipped through
> [ansible] raman service fix

- jetson/science_bridge/src/__main__.py
(relatively major please review)
> [esw] change mapping of uv bulb

- jetson/nav/environment.cpp
- jetson/nav/search/searchStateMachine.cpp
- jetson/nav/stateMachine.cpp
for circ we need to drive to any AR tag and then report the ID of the tag
> [nav] drives to any AR tag we see (for CIRC)

- base_station/download_map/src/__main__.py
- base_station/gui/src/components/AutonRoverMap.vue
- base_station/gui/src/components/SARoverMap.vue
- base_station/gui/src/components/SATask.vue
- base_station/gui/src/components/SAWaypointEditor.vue
- base_station/gui/src/components/SAWaypointItem.vue
- base_station/gui/src/store/index.js
- base_station/gui/src/store/modules/sa.js
Map was changed to png because I finally figured out how to get map data directly from google satellite view. AWS Bucket has been updated with google maps data for CIRC. 
Someone with a working vagrant/jarvis needs to test this with the lcm bridge running and make certain that the map works as intended, I was unable to get jarvis working but was able to build the GUI using webpack. This meant I was able to run the GUI but no LCM bridge.
> [teleop] Added Map to SA GUI, changed offline map format to png
