simulators/nav/src/components/App.html, simulators/nav/testing/test_dummy.json
This change adds the ability to download the current simulator field as a test case in the form of a json object which can be directly uploaded to the simulator to test the same exact set of waypoints, rocks, and tennis balls.
=> [nav] add test case download ability to simulator

config/nav/config.json, simulators/nav/src/main.js
This patch updates the nav stack to use 'autonomous' as the joystick lcm channel rather than 'drive_control'.
=> [nav] Change lcm joystick channel in nav stack

config/nav/config.json, onboard/nav/rover.cpp, simulators/nav/src/components/SimulatorField.html
This change adds scaling constants to the bearing and driving components
to the joystick message. These constants can be changed in the config file.
This change also removes the negative sign on the forward_back component
of the joystick command.
=> [nav] Added config option to scale bearing and driving constant

jarvis
replaces forward slash in first argument to exec with underscores and trims trailing underscores
should no longer interfere with successive arguments 
e.g `jarvis exec lcm_tools_echo Encoder /encoder` will behave as expected.
=> [Jarvis] Revised: Jarvis exec now accepts build dirs

onboard/cv/main.cpp
Fixes bug found during testing where obstacle distance was never actually updated when an obstacle was detected by the sliding window algorithm.
=> [cv] update LCM distance field if obstacle is detected

onboard/cv/main.cpp, onboard/nav/obstacle_avoidance/simpleAvoidance.cpp, onboard/nav/obstacle_avoidance/simpleAvoidance.hpp, onboard/nav/rover.cpp, onboard/nav/search/searchStateMachine.cpp, onboard/nav/search/searchStateMachine.hpp, onboard/nav/stateMachine.cpp, onboard/nav/stateMachine.hpp, onboard/nav/utilities.cpp, onboard/nav/utilities.hpp, rover_msgs/Obstacle.lcm, simulators/nav/src/components/perception/obstacle_detector.ts, simulators/nav/src/store/modules/roverState.ts, simulators/nav/src/utils/types.ts
resolves #355 and #356 
This commit updates the interaction between `onboard/nav` and `onboard/cv` in regards to `Obstacle` LCM messages. It also deprecates the `detected` variable in the `Obstacle` LCM in favor of using the value of the `distance` variable.
- `detected` boolean was removed from lcm
- `detected` boolean was removed from `simulators/nav`
-in nav code, `isObstacleDetected` function was created in `utilities.cpp` that
interprets a -1 obstacle distance as no obstacle detected
-cv code was updated to send distance = -1 when no obstacle
detected
=> [auton] update obstacle interface

simulators/nav/src/components/HotKeys.vue, simulators/nav/src/components/common/HeartbeatMonitor.vue, simulators/nav/src/components/control_panel/DebugTools.vue, simulators/nav/src/components/field/Field.vue, simulators/nav/src/store/modules/simulatorState.ts, simulators/nav/src/utils/types.ts
resolves #395
Add hotkeys to move the rover by clicking on the simulator
field, adjust the rover's starting position, and reset the
rover's starting position.
=> [nav-sim] Add ability to move rover and start point

jetson/percep/pcl.cpp
Greatly improved ground-plane detection using the PCL perpendicular plane segmentation model instead of the plane model. Corrected the axis being set (+y is up in the camera frame). Further improvement can be achieved by tuning the epsilon angle as needed.
=> [Percep] Improved ground-plane detection

jetson/percep/pcl.cpp, jetson/percep/pcl.hpp
Tested using the pcl images from perception-files folder. Tuned the y value upper limit until a small part of the hill top was cut off.
=> [percep] Added y axis pass through filter closes #501

admin/workflow_wiki/README.md, base_station/gui/src/components/LCMEcho.vue, base_station/gui/src/static/rover_msgs.json, config/nav/config.json, rover_msgs/ZedGimbalCommand.lcm, rover_msgs/ZedGimbalPosition.lcm, simulators/nav/src/components/HotKeys.vue, simulators/nav/src/components/NavSimulator.vue, simulators/nav/src/components/control_panel/DebugTools.vue, simulators/nav/src/components/field/Field.vue, simulators/nav/src/components/field/rover.ts, simulators/nav/src/components/hotkeys.md, simulators/nav/src/components/lcm_center/LCMCenter.vue, simulators/nav/src/components/lcm_center/ObstacleLCM.vue, simulators/nav/src/components/lcm_center/OdometryLCM.vue, simulators/nav/src/components/lcm_center/TargetListLCM.vue, simulators/nav/src/components/lcm_center/ZedGimbalLCM.vue, simulators/nav/src/components/perception/Perception.vue, simulators/nav/src/components/perception/obstacle_detector.ts, simulators/nav/src/components/perception/target_detector.ts, simulators/nav/src/store/modules/roverState.ts, simulators/nav/src/utils/constants.ts, simulators/nav/src/utils/types.ts, simulators/nav/src/utils/utils.ts
resolves #471 
This changes adds the LCM messages and channels needed for the ZED gimbal.
This change implements the simulation of the ZED gimbal in the navigation simulator and adds hotkeys for manually controlling the simulated gimbal in order to allow for richer testing.
This changes was testing by sending faked ZED gimbal command messages using the LCM send tool. Testing was done to ensure that all the affected services still built. No further integration testing was required since this was the first change related to the ZED gimbal.
=> [nav-sim] Implement ZED Gimbal

config/nav/config.json, jetson/nav/utilities.cpp, jetson/nav/utilities.hpp
Added function isObstaclePost() in utilities.cpp, called by isTargetReachable(). isTargetReachable() now returns true if the obstacle does not block the target OR if the detected obstacle is within {configurable, currently 1.5} meters of the detected tag
=> SAR-critical improvements to allow rover to reach targets when posts are detected as obstacles

jetson/percep/pcl.cpp, jetson/percep/perception.hpp
Updates default obstacle distance from `DBL_MAX` to `-1` 
- Check for:
- Check for:
- Test environment contains:
- Test for:
=> [percep] Updated default obstacle distance

config/nav/config.json, jetson/nav/gate_search/gateStateMachine.cpp, jetson/nav/rover.cpp, jetson/nav/rover.hpp, jetson/nav/search/searchStateMachine.cpp
Fixes #656 
This PR fixes the problem of having to call two separate functions to move the gimbal. Previously you had to get the gimbal object from the rover then call the set desired yaw on it. And because certain objects required for sending LCM messages were only in the scope of rover.cpp, we had another method in rover.cpp to actually send that information to the gimbal class so it could publish the message
This PR creates a new method in the rover class that handles both the setting of gimbal yaw and publishing the LCM command (both through calling functions in the gimbal class). This prevents the user from having to access the gimbal object directly and also prevents the user from having to make two function calls.
This code has been tested in the simulator
=> [Nav] Gimbal: Removes redundant gimbal call

.travis.yml, lcm_tools/send/project.ini
Added the rover_msgs dependency to lcm_tools/send, which was causing its build to fail, and consequently the travis check to fail. 
Normally lcm_tools/common would build before lcm_tools/send and lcm_tools/common has a dependency on rover_msgs, so it would build rover_msgs. However, lcm_tools/common started building after lcm_tools/send for some reason and we got the build bug. 
Started pulling the docker image from umrover1 dockerhub user instead of umrover user because we don't have the login credentials for the umrover user and cannot recover them
=> [jarvis] Fixed failing build dependency of lcm_tools/send

config/filter/config.json, jetson/filter/src/__main__.py, jetson/filter/src/inputs.py, jetson/mp9250_bridge/main.cpp
Added a new filter mode that passes bearing data from the IMU and a static GPS position to odometry. We can use this for integration testing near the AR tag without going outside or having the GPS connected.
=> GPS Spoof for localization filter

jarvis
Addded support for -gdb option for jarvis exec. Example usage: `./jarvis exec -gdb jetson/percep`
=> Jarvis debugger

jetson/nav/rover.cpp
Code to make sure we are initializing the perception data (targets and obstacles) properly to avoid issues if we are not getting LCM information from percep, and to reduce joystick power by 25%.
=> [nav] Fixes from rover testing on 2/6

config/nav/config.json, jetson/nav/rover.hpp, jetson/nav/search/searchStateMachine.cpp, jetson/nav/search/searchStateMachine.hpp, jetson/nav/stateMachine.cpp
Removed `SearchSpin` and `SearchSpinWait` states to reduce time spent searching. Also made changes to thresholds per request so that we have more accurate control/results.
=> [nav] Search SM Fixes + Clean-Up

base_station/gui/src/components/RoverMapAuton.vue
Can now zoom in two more times to map than prior. Note that the two furthest zoom levels will have lower quality mapping due to no new tile layers being used.
=> [GUI] Added zoom beyond native tilemap zoom to auton gui rover map

base_station/gui/src/components/RoverMapAuton.vue
This is an example of the gui, this was done after sending one message with the rough coordinates of Ann Arbor. Now operators will not have to find the rover each time the gui is refreshed.
=> [GUI] Auton map will now center on rover after first odom lcm message is sent

jetson/ra_kinematics/mrover_arm.cpp, jetson/ra_kinematics/mrover_arm.hpp
- Automatically set state to closed-loop when we tell the arm to move
- Safety check if closed-loop was aborted or other unexpected state is encountered before updating control state
=> Additional checks regarding control state in IK

base_station/gui/src/components/AutonModeCheckbox.vue, base_station/gui/src/components/WaypointEditor.vue
Button will now turn yellow when toggling auton mode on or off and indicated which it is trying to be set to. After receiving a message with the proper nav status the button will turn red/green. Descriptions of behavior below.
Off -> On: the button will turn yellow and read "Setting to true", then turn green once a nav status other than "Off" is received.
On -> Off: the button will turn yellow and read "Setting to false", then turn red once an "Off" nav status is received.
Note that the button can still be clicked again while in a yellow state and it will switch to the other transition state.
=> [Auton-GUI] Added intermediate step between toggling auton mode

jetson/ra_kinematics/motion_planner.cpp, jetson/ra_kinematics/motion_planner.hpp, jetson/ra_kinematics/mrover_arm.cpp, jetson/ra_kinematics/mrover_arm.hpp, jetson/ra_kinematics/utils.cpp
- Set target angle exactly equal to starting angle if they're close enough
- Change motion planner threshold to match threshold used in above
- Break out of motion planner if it takes too long
- A few missing `std::` scope specifiers
=> Fix motion planner to keep joints stationary if starting and target angles are the same

config/percep/config.json, jetson/percep/CMakeLists.txt, jetson/percep/artag_detector.cpp, jetson/percep/artag_detector.hpp, jetson/percep/camera.cpp, jetson/percep/camera.hpp, jetson/percep/main.cpp
Previously we were using just the pixel information + camera FOV to calculate bearing. Distance was calculated using the depth, so it was actually inaccurate and would be worse the less aligned you were with the gate. Now the actual point cloud information from the ZED is being used to calculate both of these better.
The intent of these fixes were to improve the accuracy of nav's estimation of gate positions since it uses both of these values. They should still be filtered on nav's end.
=> [percep -> nav] Use point cloud to better retrieve AR tag distance and bearing

config/nav/config.json, jetson/nav/gate_search/gateStateMachine.cpp
While the rover was going to the prep point it saw the target and regenerated an incorrect gate position. Try to mitigate this by:
1) Increasing the filter size from 4 to 8
2) Not allowing gate path regeneration while going to the prep point
=> [nav] Lower chance gate will be regenerated incorrectly

simulators/nav/src/components/HotKeys.vue, simulators/nav/src/components/NavSimulator.vue, simulators/nav/src/components/control_panel/SimSettings.vue, simulators/nav/src/store/modules/simulatorState.ts, simulators/nav/src/utils/types.ts
https://user-images.githubusercontent.com/71047773/178129199-fa585e46-e113-45a0-8d0c-e993342a2793.mov
Added a toggle in the current sim that freezes the rover. When 'simulating auton drive control' is turned off, the sim ignores values from the drive LCM and sets the rover velocity to 0.
This old [PR](https://github.com/umrover/mrover-workspace/pull/1115) that updated sim to the new enable interface probably got lost while merging into main. I have added the same changes in this PR
=> [sim] Added 2dsim feature to ignore auton drive control with a button + updated sim to the new enable interface
